ALTER TABLE [Test] ADD ShowVideoFiles BIT NOT NULL CONSTRAINT DF_Test_ShowVideoFiles DEFAULT 1;
GO
ALTER TABLE [Test] DROP CONSTRAINT DF_Test_ShowVideoFiles;
GO

ALTER TABLE [Test] ADD ShowAudioFiles BIT NOT NULL CONSTRAINT DF_Test_ShowAudioFiles DEFAULT 1;
GO
ALTER TABLE [Test] DROP CONSTRAINT DF_Test_ShowAudioFiles;
GO