update SYS_Usuario set usu_senha = 'MBU0wZ7xE6A=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA6033185')
update SYS_Usuario set usu_senha = '15KzzXoYrZg=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA6057628')
update SYS_Usuario set usu_senha = 'KjpB3fohBlM=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7739275')
update SYS_Usuario set usu_senha = 'j8IPOtgrzG0=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA6042108')
update SYS_Usuario set usu_senha = 'ZGuGghxC9so=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7739246')
update SYS_Usuario set usu_senha = 'DLitm04r+G4=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4952513')
update SYS_Usuario set usu_senha = 'c3WaMr/uOEQ=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4675357')
update SYS_Usuario set usu_senha = 'BCGy14Utm44=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5511949')
update SYS_Usuario set usu_senha = 'ESWHMFOpOSs=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5704536')
update SYS_Usuario set usu_senha = 'i/9RsdAY2rg=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5705453')
update SYS_Usuario set usu_senha = 'XM7U9hWB8Kc=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA6297937')
update SYS_Usuario set usu_senha = 'RixmlKba5C4=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5971957')
update SYS_Usuario set usu_senha = '/oYEolo2Bx0=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA6339920')
update SYS_Usuario set usu_senha = '4JzqapzbX9Y=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5767058')

update SYS_Usuario set usu_senha = 'D1A5mK9DUiU=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7721751')
update SYS_Usuario set usu_senha = '4k386P+FSB8=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5638474')
update SYS_Usuario set usu_senha = 'Gk8cT+8cNJI=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7737290')
update SYS_Usuario set usu_senha = 'A/vK98Z4Voo=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4669120')
update SYS_Usuario set usu_senha = 'WZcuNg955Jo=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5067726')
update SYS_Usuario set usu_senha = 'tbLoFYjppXg=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5839951')

