

update SYS_Usuario set usu_senha = 'GpxpiYhVDnk=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5098757')
update SYS_Usuario set usu_senha = 'ySRdYfeOjxs=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5164788')
update SYS_Usuario set usu_senha = '86Ex8jUyjAw=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7746934')
update SYS_Usuario set usu_senha = '981v7RdFG2g=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7725065')
update SYS_Usuario set usu_senha = 's/sZ/yPQ4lc=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5285685')
update SYS_Usuario set usu_senha = 'MuozT0274ZI=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4728213')
update SYS_Usuario set usu_senha = 'WVkoOIbjJ8Q=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7668926')
update SYS_Usuario set usu_senha = '2h3UbNPEG7M=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7732569')
update SYS_Usuario set usu_senha = 'GYQ9sy4KxQU=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7661703')
update SYS_Usuario set usu_senha = 'THLc+x3DSeY=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4872479')
update SYS_Usuario set usu_senha = '6FSeaXoHMbE=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5035342')
update SYS_Usuario set usu_senha = 'ryW1ML9ndkk=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5320946')
update SYS_Usuario set usu_senha = 'ZYE6rBmk1N0=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA3125825')
update SYS_Usuario set usu_senha = 'S3S4hp3xENw=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4276261')
update SYS_Usuario set usu_senha = 'J25VoMQKzAU=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5102522')
update SYS_Usuario set usu_senha = 'UyawFTRuLAY=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4908080')
update SYS_Usuario set usu_senha = '0x53iECC8Gw=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4501695')
update SYS_Usuario set usu_senha = 'XLK9Mu6O6gg=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5129467')
