IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'test' AND COLUMN_NAME = 'BlockChain') BEGIN
	ALTER TABLE test ADD BlockChain BIT DEFAULT '0';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'test' AND COLUMN_NAME = 'BlockChainNumber') BEGIN
	ALTER TABLE test ADD BlockChainNumber INT DEFAULT '0';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'test' AND COLUMN_NAME = 'BlockChainItems') BEGIN
	ALTER TABLE test ADD BlockChainItems INT DEFAULT '0';
END;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'test' AND COLUMN_NAME = 'BlockChainForBlock') BEGIN
	ALTER TABLE test ADD BlockChainForBlock INT DEFAULT '0';
END;
