
CREATE TABLE TestContext(
Id BIGINT IDENTITY (1, 1) NOT NULL,
Title VARCHAR(100) NULL,
Text VARCHAR(500) NULL,
ImagePath VARCHAR(500) NULL,
ImagePosition int NULL,
CreateDate DATETIME NOT NULL,
UpdateDate DATETIME NOT NULL,
Test_Id BIGINT NOT NULL,
State TINYINT NOT NULL,
 CONSTRAINT [PK_dbo.TestContext] PRIMARY KEY CLUSTERED ([Id] ASC)
)