USE [GestaoAvaliacao_SGP]
GO

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
BEGIN TRANSACTION

GO
CREATE NONCLUSTERED INDEX [IX_MTR_MatriculaTurma_tur_id_mtu_situacao>]
ON [dbo].[MTR_MatriculaTurma] ([tur_id],[mtu_situacao])

GO

CREATE NONCLUSTERED INDEX [IX_MTR_MatriculaTurma_tur_id]
ON [dbo].[MTR_MatriculaTurma] ([tur_id])

GO
CREATE NONCLUSTERED INDEX [IX_TUR_Turma_tur_situacao]
ON [dbo].[TUR_Turma] ([tur_situacao])
INCLUDE ([tur_id],[tur_codigo],[ttn_id])

GO
IF @@ERROR<>0 AND @@TRANCOUNT>0 ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT=0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors) 
  ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 
  BEGIN
    PRINT 'The database update succeeded'
    COMMIT TRANSACTION
  END
ELSE 
  PRINT 'The database update failed - ROLLBACK aplied'
GO
DROP TABLE #tmpErrors 
GO