CREATE TABLE StudentTestSent
(
	Id BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CreateDate DATETIME NOT NULL,
	UpdateDate DATETIME NULL,
	[State] TINYINT NOT NULL,
	TestId BIGINT NOT NULL,
	TurId BIGINT NOT NULL,
	AluId BIGINT NOT NULL,
	EntId UNIQUEIDENTIFIER NOT NULL,
	Vision SMALLINT NOT NULL,
	Situation SMALLINT NOT NULL
);
GO

CREATE UNIQUE INDEX UX_StudentTestSent_TestId_TurId_AluId ON StudentTestSent (TestId, TurId, AluId);