update SYS_Usuario set usu_senha = 'Bz3Ft1tyXoo=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5132021')
update SYS_Usuario set usu_senha = '+jk8FHKAIDc=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7805804')
update SYS_Usuario set usu_senha = '7ZcsYXLRGbc=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7742939')
update SYS_Usuario set usu_senha = 'Ek3qUlxlURo=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4501962')
update SYS_Usuario set usu_senha = 'rWaqNCir7uA=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4352157')
update SYS_Usuario set usu_senha = 'LAgnxzz4F8E=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5530761')
update SYS_Usuario set usu_senha = 'PUAizf0rAX0=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7746935')