update SYS_Usuario set usu_senha = 'R1TlLL8MXvQ=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5182245')
update SYS_Usuario set usu_senha = 'pYepP2+nA8I=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA7613235')
update SYS_Usuario set usu_senha = 'y3rJ2TMK9tc=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5181561')
update SYS_Usuario set usu_senha = 'E7oABn24D+Q=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5785167')
update SYS_Usuario set usu_senha = 'mU3j4Ksm/BU=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA5800835')
update SYS_Usuario set usu_senha = 'rhHbn5P82Hs=', usu_criptografia = 1 where usu_id = (select usu_id from SYS_Usuario where usu_login = 'RA4913453')
